config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  get 'ourservices/index'

  resources :managedforms
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'subscription/index'
  get 'aboutus/index'  
  resources :home, only: [:index]
  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    validates_presence_of :full_name, :phone, :email, :date1
end

app/models/managedform.rb
class Managedform < ApplicationRecord
    validates_presence_of :full_name, :phone, :email, :withdrawals, :experience,:goals, :risk, :net_worth, :family_assets, :income, :wchance    
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    def new
        @appointment = Appointment.new
    end
    def create
        @appointment = Appointment.new(appointment_params)
        if !verify_recaptcha(model: @appointment) || !@appointment.save
            render 'new'
        elsif @appointment.save
            flash[:notice] = "Thank you for your interest, we will follow up with you shortly!"
            redirect_to root_path
        end
    end

    private
    def appointment_params
        params.require(:appointment).permit(:full_name, :phone, :email, :date1, :date2, :date3, :addtninfo)        
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @morrisonpartners = []
        @value = 25000
        (0..25).each do |years|
            @value = (@value+1000) * 1.16
            @morrisonpartners << [years,@value.round(2)]
        end
        @banks = []
        @value = 25000
        (0..25).each do |years|
           @value = (@value+1000) * 1.0125
            @banks<< [years,@value.round(2)]
        end    
        @etfs = []
        @value = 25000
        (0..25).each do |years|
           @value = (@value+1000) * 1.1325
            @etfs<< [years,@value.round(2)]
        end 
        @investments = [{name: 'Morrison&Partners', data: @morrisonpartners}, {name: 'Other Investment Managers', data: @etfs}, {name: 'Savings Account', data: @banks}]           
    end
end

app/controllers/managedforms_controller.rb
class ManagedformsController < ApplicationController
  def new
    @managedform = Managedform.new
  end
  def create
    @managedform = Managedform.new(managedform_params)
    if !verify_recaptcha(model: @managedform) || !@managedform.save
      render 'new'
    elsif @managedform.save
      flash[:notice] = "Thank you for your interest, we will follow up with you shortly!"      
      redirect_to root_path
    end
  end
  private

    def managedform_params
      params.require(:managedform).permit(:full_name, :phone, :email, :withdrawals, :experience,:goals, :risk, :net_worth, :family_assets, :income, :wchance)
    end
end

app/controllers/ourservices_controller.rb
class OurservicesController < ApplicationController
  def index
  end
end

app/controllers/subscription_controller.rb
class SubscriptionController < ApplicationController
  def index
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managedforms_helper.rb
module ManagedformsHelper
end

app/helpers/ourservices_helper.rb
module OurservicesHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/aboutus/index.html.erb
<div class="d-flex justify-content-center">
<div class="column col-sm-12 col-md-10 col-lg-7">
  <div class="column col-12 mt-2">
    <div class="card cardbg">
      <div class="container d-flex justify-contents-around businesscard" >
        <div class="pt-3"><%= image_tag 'brucemorrison.png', alt: "Bruce" %></div>
        <div class="card-body pb-0">
        <h2>Bruce Morrison CIM, FCSI</h2>
        <p class="title">Portfolio Manager, Executive Director, Private Client Group</p>
        <p>bruce.morrison@holliswealth.com</p>
        <div class="d-flex justify-content-end">
        <p><button class="btn btn-raised bio">Bruce's Bio</button></p>
        </div>
        </div>
      </div>
    </div>
  </div>

  <div class="column col-12 mt-2">
    <div class="card cardbg">
      <div class="container d-flex justify-contents-around businesscard">
        <div class="pt-3"><%= image_tag "mikemorrisonpartners.png", alt: "Mike" %></div>
        <div class="card-body pb-0">
        <h2>Mike Brintnell FCSI, CIM</h2>
        <p class="title">Portfolio Manager</p>
        <p>m.brintnell@holliswealth.com</p>
        </div>
      </div>
    </div>
  </div>

  <div class="column col-12 mt-2">
    <div class="card cardbg">
      <div class="container d-flex justify-contents-around businesscard">
        <div class="pt-3"><%= image_tag "dustinmorrisonpartners.png", alt: "Dustin" %></div>
        <div class="card-body pb-0">
        <h2>Dustin Pierce CPA, CA, CFA</h2>
        <p class="title">Portfolio Analyst</p>
        <p>dustin.pierce@holliswealth.com</p>
        </div>
      </div>
    </div>
  </div>

    <div class="column col-12 mt-2">
    <div class="card cardbg">
      <div class="container d-flex justify-contents-around businesscard">
        <div class="pt-3"><%= image_tag "jaymorrisonpartners.png", alt: "Dustin" %></div>
        <div class="card-body pb-0">
        <h2>Jay DeBoice B.Comm, CIM</h2>
        <p class="title">Portfolio Manager</p>
        <p>jay.deboice@holliswealth.com</p>
        </div>
      </div>
    </div>
  </div>
    <div class="column col-12 mt-2">
    <div class="card cardbg">
      <div class="container d-flex justify-contents-around businesscard">
      <div class="pt-3"><%= image_tag "stevemorrisonpartners.png", alt: "Dustin" %></div>
        <div class="card-body pb-0">
        <h2>Steve Ambeault CPA, CA</h2>
        <p class="title">Financial Planning Associate</p>
        <p>steve.ambeault@holliswealth.com</p>
        </div>
      </div>
    </div>
  </div>
    <div class="column col-12 mt-2">
    <div class="card cardbg">
      <div class="container d-flex justify-contents-around businesscard">
      <div class="pt-3"><%= image_tag "janmorrisonpartners.png", alt: "Dustin" %></div>
        <div class="card-body pb-0">
        <h2>Jan Morrison</h2>
        <p class="title">Office Manager</p>
        <p>jan.morrison@holliswealth.com</p>
        </div>
      </div>
    </div>
</div>
</div>

app/views/appointments/new.html.erb
<div class="container col-sm-12 col-md-8 col-lg-7 mt-5 mb-5">
<h4 class="pt-4">Request an Appointment</h4>
<%= simple_form_for(@appointment, local: true) do |form| %>
<% if @appointment.errors.any? %>
  <div id="error_explanation">
    <h6><%= pluralize(@appointment.errors.count, "error") %> prohibited your form from being saved:</h6>
    <ul>
      <% @appointment.errors.full_messages.each do |message| %>
          <li class="alert alert-danger" role="alert"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="row">
  <div class="col-12"><%= form.input :full_name, id: :appointment_full_name, label: "Full Name" %></div>
  </div>
  <div class="row d-flex justify-content-between">
  <div class="col-6"><%= form.input :phone, id: :appointment_phone, label: "Phone/Cell" %></div>
  <div class="col-6"><%= form.input :email, id: :appointment_email, label: "E-Mail" %></div>
  </div>
  <div class="row">
    <div class="col-12"><%= form.input :addtninfo, label: "Additional Information", input_html:{ rows:  5 } %></div>
  </div>
<h4>Please specify 3 dates and time that work best for you:</h>
<div class="row pt-4">
    <div class="col-md-12">
        <div><h4>Preferred Date #1</h4></div>
        <div><%= form.text_field :date1, label: "First Available Date", class: 'datetimepicker' %></div>
    </div>
    <div class="col-md-12">
        <div><h4>Preferred Date #2</h4></div>
        <div><%= form.text_field :date2, label: "First Available Date", class: 'datetimepicker' %></div>
    </div>
    <div class="col-md-12">
        <div><h4>Preferred Date #3</h4></div>
        <div><%= form.text_field :date3, label: "First Available Date", class: 'datetimepicker' %></div>
    </div>
</div>
  <div>
    <br />
    <div class="d-flex justify-content-center"><%= recaptcha_tags %></div>
    <br />
  </div>
  <div class="actions pb-5">
    <%= form.submit "Request an appointment", class: "btn btn-primary btn-raised col-12" %>
  </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="container pb-4">
<div class="jumbotron d-flex justify-content-center header-jumbo-home flex-column">
  <div class="justify-content-center align-items-center">
    <div class="d-flex justify-content-center">  
        <h1 class="display-5 animated fadeIn">Who is truly managing your money?</h1>
    </div>
    <div class="d-flex justify-content-center pt-2">
            <%= link_to 'Read More', "http://morrisonpartners.com/wp-content/uploads/2011/05/MORRISON-booklet-Web-July-13-11.pdf", class: "btn btn-primary btn-raised header-button-width" %>
    </div>
  </div>
</div>
    <div class="row mt-4">
        <div class="col-sm-12 col-md-8, col-lg-6">
            <div class="card">
            <div class="card-body homecard">
                <h4 class="card-title">Your video goes here</h4>
                <%= image_tag "morrisonpartnerswireframevox.jpg", class:'col-12'%>
            </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-4, col-lg-6">
            <div class="card">
            <div class="card-body homecard">
                <h4 class="card-title">“The most expensive thing you can own is a closed mind.”</h4>
                <p class="card-text">Welcome existing clients and future clients. To find out more about my professional services, please refer to our services page. I look forward to helping you reduce the noise and to simplify the wealth management process.</p>
                <div class="card-footer mt-5"><%= image_tag "cipf.png", alt: '', class: "mr-2" %><%= image_tag "renamediiroc.png", class:"col-7" %><%= image_tag "morrisonpartnersknowyouradvisor.png", alt: '' %></div>
            </div>
            </div>
        </div>
    </div>
    <div class="card col-12 mt-4 pb-4">
        <div class="row d-flex justify-contents-around">
            <div class="col-lg-4 col-md-12 col-sm-12">
                <div class="card-header"><h3>Investing with us</h3></div>
                <div class="card-body d-flex">
                    <div class="col-8">
                        <div>Initial Investment</div>
                        <div>Monthly Contribution</div>
                        <div>Time Period</div>
                    </div>
                    <div class="col-4">
                        <div>$25,000</div>
                        <div>$1,000</div>
                        <div>25 years</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 col-md-12 col-sm-12">
            <%= area_chart @investments, points: false, legend: "top"%>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('morrisonpartners.ico'), :rel => 'icon', :type =>  'image/png' %>
    <title>Morrison Partners</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "//www.google.com/jsapi" %>
   </head>

  <body>
  <nav class="navbar navbar-light border-bottom-0 navcolor d-flex justify-content-center">
    <div class="d-flex justify-content-between col-sm-12 col-md-12 col-lg-10">
    <a class="navbar-brand" href="#">
      <%= image_tag('morrisonpartnerslogo.jpg', height:"40") %>
    </a>
    <a class="navbar-brand" href="#">
      <%= image_tag('holliswealthlogo.jpg', height:"40") %>
    </a>
    </div>
  </nav>
  <nav class="navbar navbar-expand-sm navbar-light navcolor d-flex justify-content-center p-0" id="nav_bar">
    <div class="d-flex justify-content-between col-sm-12 col-md-12 col-lg-11 pl-5">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'About Us', aboutus_index_path , class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Our Services', ourservices_index_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Market Outlook</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Next Steps
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Contact Us</a>
              <%= link_to 'Request an Appointment', new_appointment_path, class: "dropdown-item"  %>
              <%= link_to 'Managed Questionnaire', new_managedform_path, class: "dropdown-item" %>
              <a class="dropdown-item" href="#">Our Group Benefits Plan</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    <div class="container-fluid p-0">
      <% if flash[:notice].present? %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:alert].present? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
      <%= yield :charts_js %> <!-- Rails -->
    </div>
      <footer id="myFooter">
        <div class="container pb-5" style="background-color:#ffffff;">
            <ul class="pt-4">
                <li><a href="#">Company Information</a></li>
                <li><a href="#">Contact us</a></li>
                <li><a href="#">Terms of service</a></li>
            </ul>
        <p class="footer-copyright m-0">© 2018 Morrison&Partners</p>
        <p class="footer-copyright m-0 indemnity">HollisWealth® is a division of Industrial Alliance Securities Inc., a member of the Canadian Investor Protection Fund and the Investment Industry Regulatory Organization of Canada. Morrison & Partners Wealth Strategies is a personal trade name of Bruce Morrison. The particulars contained herein were obtained from sources which we believe are reliable, but are not guaranteed by us and may be incomplete. The opinions expressed have not been approved by and are not those of HollisWealth. This website is not deemed to be used as a solicitation in a jurisdiction where this HollisWealth representative is not registered.</p>
        </div>
    </footer>
  </body>
</html>

app/views/managedforms/_form.html.erb
<div class="container col-6">
<%= simple_form_for(@managedform, local: true) do |form| %>
  <% if managedform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(managedform.errors.count, "error") %> prohibited this your form from being saved:</h2>

      <ul>
      <% managedform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.input :full_name, id: :managedform_full_name %>
    <%= form.input :phone, id: :managedform_phone %>
    <%= form.input :email, id: :managedform_email %>
    <%= form.input :withdrawals, id: :managedform_withdrawals %>
    <%= form.input :experience, id: :managedform_experience %>
    <%= form.input :risk, id: :managedform_risk %>
    <%= form.input :assets, id: :managedform_assets %>
    <%= form.input :income, id: :managedform_income %>
    <%= form.input :wchance, id: :managedform_wchance %>
  <div>
    <br />
      <%= recaptcha_tags %>
    <br />
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/managedforms/new.html.erb
<div class="container col-sm-12 col-md-8 col-lg-7 mt-5 mb-5">
<h4 class="pt-3">Investor Questionnaire </h4>
<%= simple_form_for(@managedform, local: true) do |form| %>
  <% if @managedform.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@managedform.errors.count, "error") %> prohibited this your form from being saved:</h6>
      <ul>
        <% @managedform.errors.full_messages.each do |message| %>
            <li class="alert alert-danger" role="alert"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="row d-flex justify-content-between">
    <div class="col-12"><%= form.input :full_name, id: :managedform_full_name, label: "Full Name", class: "formfields" %></div>
    </div>
    <div class="row d-flex justify-content-between">
    <div class="col-6"><%= form.input :phone, id: :appointment_phone, label: "Phone/Cell", class: "formfields" %></div>
    <div class="col-6"><%= form.input :email, id: :appointment_email, label: "E-Mail", class: "formfields" %></div>
    </div>
    <h4>When do you anticipate you will need to start drawing on this money?</h4>
    <div class="btn-group-lg d-flex flex-column" data-toggle="buttons">  
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :withdrawals, 'More than 10 years'%><%= form.label 'More than 10 years', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :withdrawals, '5 - 10 years' %> <%= form.label '5-10 years', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :withdrawals, '3 - 4 years' %> <%= form.label '3-4 years', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :withdrawals, '1 - 2 years' %> <%= form.label '1-2 years', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :withdrawals, 'Less than 1 year' %> <%= form.label 'Less than 1 year', class: "pl-2" %></div>
    </div>
    <h4>Which of the following would you say best reflects your current knowledge of, and experience with investing?</h4>
    <div class="btn-group-lg d-flex flex-column" data-toggle="buttons">  
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :experience, 'Sophisticated' %> <%= form.label 'Sophisticated', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :experience, 'Good' %> <%= form.label 'Good', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :experience, 'Average' %> <%= form.label 'Average', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :experience, 'Limited' %> <%= form.label 'Limited', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :experience, 'Very Low' %> <%= form.label 'Very Low', class: "pl-2" %></div>
    </div>
    <h4>Which would you say best describes your investment goals?</h4>
    <div class="btn-group-lg d-flex flex-column" data-toggle="buttons">  
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :goals, 'Aggressive Growth' %> <%= form.label 'Aggressive Growth', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :goals, 'Growth' %> <%= form.label 'Growth', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :goals, 'Income & Growth' %> <%= form.label 'Income & Growth', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :goals, 'Short-Term Yield' %> <%= form.label 'Short-Term Yield', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :goals, 'Income' %> <%= form.label 'Income', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :goals, 'Security' %> <%= form.label 'Security', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :goals, 'Alpha' %> <%= form.label 'Alpha', class: "pl-2" %></div>
    </div>
    <h4>How would you describe your comfort level should the value of your investments decline in the short term?</h4>  
    <div class="btn-group-lg d-flex flex-column" data-toggle="buttons">    
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :risk, 'Very High' %> <%= form.label 'Very High', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :risk, 'High' %> <%= form.label 'High', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :risk, 'Moderate' %> <%= form.label 'Moderate', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :risk, 'Low' %> <%= form.label 'Low', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start button-text"><%= form.radio_button :risk, 'Very Low' %> <%= form.label 'Very Low', class: "pl-2" %></div>
    </div>
    <h4>Within what range would you estimate your net worth, excluding your principle residence?</h4>
    <div class="btn-group-lg d-flex flex-column" data-toggle="buttons">    
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :net_worth, 'Over $500K' %> <%= form.label 'Over $500K', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :net_worth, '$200K - $500K' %> <%= form.label '$200K - $500K', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :net_worth, '$50K - $199K' %> <%= form.label '$50K - $199K', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :net_worth, 'Under $50K' %> <%= form.label 'Under $50K', class: "pl-2" %></div>
    </div>
    <div class="btn-group-lg d-flex flex-column" data-toggle="buttons">
    <h4>What level of assets will your family be investing with us?</h4>
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :family_assets, 'Less Than $1 Million' %> <%= form.label 'Less Than $1 Million', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :family_assets, '$1 Million - $2 Million' %> <%= form.label '$1 Million - $2 Million', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :family_assets, 'Greater Than $2 Million' %> <%= form.label 'Greater Than $2 Million', class: "pl-2" %></div>
    </div>
    <h4>Within what range would you estimate your annual income?</h4>
    <div class="btn-group-lg d-flex flex-column" data-toggle="buttons">
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :income, 'Over $150K' %> <%= form.label 'Over $150K', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :income, '$75K - $150K' %> <%= form.label '$75K - $150K', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :income, '$50K - $74.9K' %> <%= form.label '$50K - $74.9K', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :income, 'Under $50K' %> <%= form.label 'Under $50K', class: "pl-2" %></div>
    </div>
    <h4>What is the likelihood that you will need to draw on the money invested in this account before your expected investment time horizon?</h4>
    <div class="btn-group-lg d-flex flex-column" data-toggle="buttons">
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :wchance, 'Entirely Unlikely' %> <%= form.label 'Entirely Unlikely', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :wchance, 'Somewhat Likely' %> <%= form.label 'Somewhat Likely', class: "pl-2" %></div>
    <div class="btn btn-primary d-flex justify-content-start"><%= form.radio_button :wchance, 'Likely' %> <%= form.label 'Likely', class: "pl-2" %></div>
    </div>
  <div>
    <br />
    <div class="d-flex justify-content-center"><%= recaptcha_tags %></div>
    <br />
  </div>
  <div class="actions">
    <%= form.submit "Submit Questionnaire", class: "btn btn-primary btn-raised col-12 mb-5" %>
  </div>
<% end %>
</div>

app/views/subscription/index.html.erb
<h1>Subscription#index</h1>
<p>Find me in app/views/subscription/index.html.erb</p>